### ISSUE TITLE
Add variable to check what type of item is

### ISSUE THREAD

**Issue by SrPatinhas** [Ideneal/OpenLoad#15]
So, I was trying to list the items in the account, but when I have some variables for the items and the item is a folder, it will return an error, maybe add a variable to say if its a file or a folder.

**Comment by Ideneal** [comment]
I suppose you have used the getContents method. If so it returns a list of of AbstractContent and you can check the type of content by the instance, if the content is instance of Folder is a folder, else is a File.

If this it's not the problem, could you give me the code you have used and the related error?
