### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by KeizerDev** [Ideneal/OpenLoad#2]
I'm using Symfony within my application and I want to do file upload, this is what I got:
```
$file = $request->files->get('video-upload');
$this->openloadClient->uploadFile($file, 'id');
```
The form is set correctly and the file exist but it won't get uploaded. Why is that?

The openload stuff is also correct.

**Comment by Ideneal** [comment]
I think because the file that you pass to uploadFile method as parameter is an object instead of a path name.
Anyway, have you had any type of error?

**Comment by KeizerDev** [comment]
@Ideneal I've manage to fix it by store it on my server first and then upload it to openload. I was still hoping it could be direct to openload instead of my server first.

**Comment by Ideneal** [comment]
No it's not possible because the upload behaviour. The file must be first on your server and then you can do the upload on the openload server.
