### ISSUE TITLE
Add the OpenLoad FTP feature(feature request)

### ISSUE THREAD

**Issue by peter279k** [Ideneal/OpenLoad#8]
As title, I notice that the OpenLoad provides another way to upload the file.
It can access the files via FTP Access.
Do you have the plan to add this?
If possible, I can add this.
What do you think?

Thanks.

**Comment by Ideneal** [comment]
Hi Peter! :smiley: 
No this is not in plan because it exits from the library scope and so it's not a good practice, it's not should be implemented :)
