### ISSUE TITLE
i don't undersatnd how this works? 

### ISSUE THREAD

**Issue by Leo01985** [Ideneal/OpenLoad#9]
is posible to make some script like this https://github.com/ArdiArtani/Google-Drive-Player-Script this is for google drive, i don't know if is posible to make same for openload?

**Comment by peter279k** [comment]
Hi, thank you for your issue.
This package implements the OpenLoad API to access the user account, films and film informations.
You can also see more details about [this](https://openload.co/api) API doc.
If you want to create the viewed link like the the ```Google Driver Player```, just follow the following link format:

```
https://openload.co/f/{unique-id}/{file-name}.mp4
```
And the example link is here: https://openload.co/f/UPPjeAk--30/big_buck_bunny.mp4.mp4
You can also refer this [link](https://github.com/Ideneal/OpenLoad#get-a-ticket-to-download-a-file).

Thanks.
